// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// DO NOT remove as generated components depend on these aliases

module.exports = {
  resolve: {
    alias: {
      "@": "../parts",
      vue$: "vue/dist/vue.esm.js",
      tests: "../tests",
      locales: "../locales"
    },
    extensions: [".vue"]
  }
};
